# Site settings
title: Nazim Medzhidov, PhD
name: Nazim Medzhidov

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/nmedzhidov
 - title: LinkedIn
   url: https://www.linkedin.com/in/nazim-medzhidov-12161539/
 - title: Twitter
   url: https://twitter.com/MedzhidovND

#Any buzzword skills you want to include
skills:
 - Immunology
 - Molecular Biology
 - Building AI powered chatbots using IBM Watson APIs
 - Python
 - R basics
 - Artificial Intelligence
 - Data Science


#Blogfeed is optional - including this will add JS to call the feed and populate blog list
extras: Interesting articles

#Work experience is required
roles:
 - title: Research Scientist
   start: 2017 - Present
   end: Ongoing
   employer: Tokyo Medical and Dental University
   description: "Ever thought how our body keeps us safe from microbes? That's exactly what I am trying to figure out! I work on B lymphocytes, the cells that produce proteins called antibodies that serve as weapons against microbes. Currently, I am leading two projects:<br/><br/>
1) Together with my mentee, a talented Ph.D. candidate, we are interested in understanding the molecular mechanisms that take place when a B lymphocyte recognizes a foreign substance in the body. We are focused on the main mediator of this process, a unique receptor on the surface of a B cell, the B cell receptor (BCR). It recognizes the foreign molecule in the extracellular environment, catches and takes it inside the cell. We are curious to find out what exactly happens to BCR and the foreign molecule (antigen is the general name for it) when they both take the journey from the cell surface to the deep (and maybe dark) parts of the cell. I would say we witnessed some interesting unexpected things to happen during this journey and hopefully, soon we will be able to identify the critical roles of those events in the immune response.<br/><br/>
2) What makes some molecules induce a strong immune response while other molecules are moderate in this aspect or even unable to do so? This is another interesting question that we are trying to address with my other talented mentee, a Ph.D. candidate. We focus on chemical differences between different antigens and look at where and how those differences matter at the molecular level. Some interesting findings are on the way!"
   
#Education is required
education:
 - level: Ph.D. in Immunology
   date: 2017
   school: Tokyo Medical and Dental University
   subject: Endosomal trafficking and persistence of the antigen - B cell receptor complex and their significance in B lymphocyte activation.
 - level: MS in Molecular Biology
   date: 2013
   school: Fatih University, Istanbul, Turkey
   subject: Expression of recobinant Puumala virus endonuclease and in silico screening for small molecule inhibitors.
   description: This work was focused on in silico drug screening for inhibitors of Puumala Virus endonuclease enzyme. Two libraries of potential small molecule drug candidates were established from a public database (PubChem), a library of experimentally tested drugs against endonuclease from Influenza virus (due to similarity in structure to the Puumala endonuclease) and a library of randomly selected molecules. Both libraries were screened against active site of the Puumala endonuclease by molecular docking software Autodock Vina and binding affinities of the drug candidates to the target site were compared. New candidates with high binding affinity to the Puumla Virus endonuclease active site were identified from the test library.
 - level: Bachelor of Science
   date: 2011
   school: Fatih University, Istanbul, Turkey
   subject: Molecular Biology
#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
   courses:
    - title: Python for Data Science and AI
      link: https://www.coursera.org/learn/python-for-applied-data-science-ai
      optionalimage: ../img/Coursera Python Certificate RNMYCH7LBLUV.png
      date: Certificate earned in August 2019. 
      grade: "Grade Achieved: 98.8%." 
      background: Course offered by IBM.<br/><br/> In this course I learned how to use Python programming language to work with data.
    - title: Introduction to Computer Vision with Watson and OpenCV
      link: https://www.coursera.org/learn/introduction-computer-vision-watson-opencv
      optionalimage: ../img/Coursera Computer Vision certificate.png
      date: Certificate earned in September 2019. 
      grade: "Grade Achieved: 98.0%." 
      background: Course offered by IBM.<br/><br/> Using Python and IBM Watson Visual Recognition service I built a custom image classifier and trained a model for classification of furniture items such as chairs, tables and beds. This model was further used to build a Web application where users can upload pictures and model will attempt to classify them.
    - title: Building AI Powered Chatbots Without Programming
      link: https://www.coursera.org/learn/building-ai-powered-chatbots
      optionalimage: ../img/Coursera chatbots certificate RPQCYK637RA8.png
      date: Certificate earned in July 2019.
      grade: "Grade Achieved: 96.8%."
      background: Course offered by IBM.<br/><br/> In this course I learned about Watson Virtual Assistant services and built a chatbot for a fictional flower shop utilizing Watson APIs.
    - title: Introduction to Artificial Intelligence (AI)
      link: https://www.coursera.org/learn/introduction-to-ai
      optionalimage: ../img/Coursera Intro to AI certificate 8RXXQWDRNCGW.png
      date: Certificate earned in July 2019.
      grade: "Grade Achieved: 91.3%."
      background: Course offered by IBM.<br/><br/> This course helped me to understand how AI works, where it can be implemented and how it can help in solving complex problems.
    - title: Getting Started with AI using IBM Watson
      link: https://www.coursera.org/learn/ai-with-ibm-watson
      optionalimage: ../img/Coursera IBM Watson certificate LLVEZKHTFMS4.png
      date: Certificate earned in August 2019.
      grade: "Grade Achieved: 90%."
      background: Course offered by IBM.<br/><br/> In this course I was introduced to the various fileds where IBM Watson is applied in real life (healthcare part was the most interesting for me) and learned how to use AI services provided by IBM Watson.

#List of interesting Github repo/projects to include - optional
github:
 - NMedzhidov/nmedzhidov.github.io

#Introduction
intro: |
  I am currently doing research in Immunology focused on understanding the molecular mechanisms of B lymphocyte activation. 
  During my journey as a life scientist, I mainly worked (as many other scientsits do) on a particular protein function/mechanism. 
  This approach has served scientific community for many years, however, in the age of Big Data, enormous amount of information is being generated. 
  Together with the new technologies, this amount of data can be used to speed up the progress in biological sciences and help solving more complex problems much faster to benefit the society. 
  I want to combine my 8 years of life science research experience with Artificial Intelligence skills to generate new approaches for solving biological questions. 
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Visual Recognition Web App</strong>: Using Python and IBM Watson Visual Recognition service I built a custom image classifier and trained a model for classification of furniture items such as chairs, tables and beds. This model was further used to build a Web application where users can upload pictures and model will attempt to classify them.<br/><br/>
   <strong>AI Powered Chatbot</strong>: During my process of learning Artificial Intelligence I developed an AI based chatbot using IBM Watson API services. <a target="_blank" href="https://nazimmedzhidov.intelaedu.com"> This chatbot</a> was desgined for a fictional flower shop chain.<br/><br/>
   <strong>Python Learning</strong>: <a target="_blank" href="https://github.com/NMedzhidov/First-steps-with-Python"> Here</a> are the excercises and a small project that I completed to obtain Python for Data Sciece and AI certificate from Coursera.<br/><br/>
theme: jekyll-theme-architect
