# Site settings
title: Nazim Medzhidov, PhD
name: Nazim Medzhidov

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/nmedzhidov
 - title: LinkedIn
   url: https://www.linkedin.com/in/nazim-medzhidov-12161539/
 - title: Twitter
   url: https://twitter.com/MedzhidovND

#Any buzzword skills you want to include
skills:
 - Immunology
 - Molecular Biology
 - Building AI powered chatbots using IBM Watson APIs
 - Python basics
 - R basics
 - Artificial Intelligence
 - Data Science


#Blogfeed is optional - including this will add JS to call the feed and populate blog list
extras: Interesting articles

#Work experience is required
roles:
 - title: Postdoctoral Fellow
   start: 2017 - Present
   end: Ongoing
   employer: Tokyo Medical and Dental University
   description: I am working on the mechanisms of B cell activation.
   
#Education is required
education:
 - level: Ph.D. in Immunology
   date: 2017
   school: Tokyo Medical and Dental University
   subject: Endosomal trafficking and persistence of the antigen - B cell receptor complex and their significance in B lymphocyte activation.
 - level: MS in Molecular Biology
   date: 2013
   school: Fatih University, Istanbul, Turkey
   subject: Expression of recobinant Puumala virus endonuclease and in silico screening for small molecule inhibitors.
 - level: Bachelor of Science
   date: 2011
   school: Fatih University, Istanbul, Turkey
   subject: Molecular Biology
#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
   courses:
    - title: Python for Data Science and AI
      link: https://www.coursera.org/learn/python-for-applied-data-science-ai
      optionalimage: ../img/Coursera Python Certificate RNMYCH7LBLUV.png
      date: Certificate earned in August 2019. 
      grade: "Grade Achieved: 98.8%." 
      background: Course offered by IBM.<br/><br/> In this course I learned how to use Python programming language to work with data.
    - title: Building AI Powered Chatbots Without Programming
      link: https://www.coursera.org/learn/building-ai-powered-chatbots
      optionalimage: ../img/Coursera chatbots certificate RPQCYK637RA8.png
      date: Certificate earned in July 2019.
      grade: "Grade Achieved: 96.8%."
      background: Course offered by IBM.<br/><br/> In this course I learned about Watson Virtual Assistant services and built a chatbot for a fictional flower shop utilizing Watson APIs.
    - title: Introduction to Artificial Intelligence (AI)
      link: https://www.coursera.org/learn/introduction-to-ai
      optionalimage: ../img/Coursera Intro to AI certificate 8RXXQWDRNCGW.png
      date: Certificate earned in July 2019.
      grade: "Grade Achieved: 91.3%."
      background: Course offered by IBM.<br/><br/> This course helped me to understand how AI works, where it can be implemented and how it can help in solving complex problems.
    - title: Getting Started with AI using IBM Watson
      link: https://www.coursera.org/learn/ai-with-ibm-watson
      optionalimage: ../img/Coursera IBM Watson certificate LLVEZKHTFMS4.png
      date: Certificate earned in August 2019.
      grade: "Grade Achieved: 90%."
      background: Course offered by IBM.<br/><br/> In this course I was introduced to the various fileds where IBM Watson is applied in real life (healthcare part was the most interesting for me) and learned how to use AI services provided by IBM Watson.

#List of interesting Github repo/projects to include - optional
github:
 - NMedzhidov/nmedzhidov.github.io

#Introduction
intro: |
  I am currently doing research in Immunology field focused on understanding the molecular mechanisms of B lymphocyte activation. In parallel I am trying to gain programming skills and apply them in solving biological questions.
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>AI Powered Chatbot</strong>: During my process of learning Artificial Intelligence I developed an AI based chatbot using IBM Watson API services. <a target="_blank" href="https://nazimmedzhidov.intelaedu.com"> This chatbot</a> was desgined for a fictional flower shop chain.<br/><br/>
   <strong>Python Learning</strong>: <a target="_blank" href="https://github.com/NMedzhidov/First-steps-with-Python"> Here</a> are the excercises and a small project that I completed to obtain Python for Data Sciece and AI certificate from Coursera.<br/><br/>
theme: jekyll-theme-architect
