# Site settings
title: Nazim Medzhidov, PhD
name: Nazim Medzhidov

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/nmedzhidov
 - title: LinkedIn
   url: https://www.linkedin.com/in/nazim-medzhidov-12161539/
 - title: Twitter
   url: https://twitter.com/MedzhidovND

#Any buzzword skills you want to include
skills:
 - Immunology
 - Molecular Biology
 - Building AI powered chatbots using IBM Watson APIs
 - Python basics
 - R basics
 - Artificial Intelligence
 - Data Science


#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://www.nature.com/articles/d41586-019-01357-6

#Work experience is required
roles:
 - title: Postdoctoral Research Fellow
   start: 2017
   end: Ongoing
   employer: Tokyo Medical and Dental University
   description: 
   
#Education is required
education:
 - level: Ph.D. in Immunology
   date: 2007
   subject: B lymphocyte activation
   school: Tokyo Medical and Dental University

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
   courses:
    - title: Python for Data Science and AI
      link: https://www.coursera.org/learn/python-for-applied-data-science-ai/home/welcome
      optionalimage: ../img/Coursera Python Certificate RNMYCH7LBLUV.png
      date: Certificate earned in August 2019. 
      grade: "Grade Achieved: 98.8%." 
      background: In this course I learned how to use Python programming language to work with data.
    - title: Introduction to Artificial Intelligence (AI) by IBM
      link: https://www.coursera.org/learn/introduction-to-ai/home/welcome
      optionalimage: ../img/Coursera Intro to AI certificate 8RXXQWDRNCGW.png
      date: Certificate earned in July 2019.
      grade: Grade Achieved 91.3%.
      background: 
    - title: Building AI Powered Chatbots Without Programming by IBM
      link: https://www.coursera.org/learn/building-ai-powered-chatbots/home/welcome
      optionalimage: ../img/Coursera chatbots certificate RPQCYK637RA8.png
      date: Certificate earned in July 2019.
      grade: "Grade Achieved: 96.8%."
      background:


#List of interesting Github repo/projects to include - optional
github:
 - NMedzhidov/nmedzhidov.github.io

#Introduction
intro: |
  I am currently doing research in Immunology field focused on understanding the molecular mechanisms of B lymphocyte activation. In parallel I am trying to gain programming skills and apply them in solving biological questions.
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>AI Powered Chatbot</strong>: During my process of learning Artificial Intelligence I developed an AI based chatbot using IBM Watson API services. <a target="_blank" href="https://nazimmedzhidov.intelaedu.com"> This chatbot</a> was desgined for a fictional flower shop chain.<br/><br/>
   <strong>Python Learning</strong>: <a target="_blank" href="https://gist.github.com/NMedzhidov"> Here</a> are the gists of subjects covered during Python for Data Science and AI course.<br/><br/>
theme: jekyll-theme-architect
